#!/bin/bash

VERSION=${1:-512}
EXEC=shasum
CMD="$EXEC -a $VERSION"
SHA="sha$VERSION"

INPUT=docs/nominatim.openapi.json
OUTPUT="$INPUT".checksum

if [ ! -f $INPUT ]
then
    echo "$INPUT file is missing, abort"
    exit 1
fi

if ! command -v $EXEC &> /dev/null
then
    echo "$EXEC could not be found, please install it"
    exit 1
fi

CHECKSUM=`$CMD $INPUT | awk '{print $1}'`

if [ ! -f $OUTPUT ]
then
    echo "$OUTPUT file is missing, abort"
    exit 1
fi

if ! grep "$SHA-$CHECKSUM" $OUTPUT &>/dev/null
then
    echo "wrong checksum, please verify"
    exit 1
fi

echo "Checksum ($OUTPUT): $SHA-$CHECKSUM"
exit 0
