#!/bin/bash

VERSION=512
CMD=shasum
SHA="sha$VERSION"

INPUT=docs/nominatim.openapi.json
OUTPUT="$INPUT".checksum

if [ ! -f $INPUT ]
then
    echo "$INPUT file is missing, abort"
    exit 1
fi

if ! command -v $CMD &> /dev/null
then
    echo "$CMD could not be found, please install it"
    exit 1
fi

CHECKSUM=`$CMD -a $VERSION $INPUT | awk '{print $1}'`

echo "Checksum ($OUTPUT): $SHA-$CHECKSUM"
echo -n "$SHA-$CHECKSUM" > $OUTPUT
git add $OUTPUT
exit 0
